travis:
  secure:
    BINSTAR_TOKEN: AiqEKCsTupB3C7llx19aGz1dYPjBsqEkVh9iBOUiqT2Lb4rGtl62gGZz9LtmNfgOpRiy8tgEIEisSzzbeTKhgDpUsDTzKYxOycj9rmsFKifp5lwXiWd+Vhwh7sYPXw5BBfYKVTyTF5E1YbigXs88999kOvssD+GY4cCEx2lBEWabw4C+K17Qe+LItcv39CVheLn+6PdwAYVmifhp4dkJNoxZL1H9sStoOEISYGek5k7qkZ31FOd/KnUSSH4jVczaMZQNTZDv80DO+P+nOAiFPXFpMkNEO1TrJug8Fi8e4HSTqvHZxDgTYNSbnJ12qPQFM0POmiDTOFM7CkUCVrted9RKaOCBN+mf7UuydSYHwjSDU5+tEHqxveEAKVKyr5wNdx8XFUUBXdwkiUH6KpIw0hnh5CITAgEiVke1xE9bLjcJA2G+wervZ6oheDvOEy+/Jx6VUDGg1d3BgdB9mkcqtej4UJG3x6L217WxFQogFE9gWXRFGaCCAer5rAhW6u8r+o4lzH9JDWe6UR7/NKJ/meFQpKDUH7O32unSopH/qpbA3YaFRLqYiIEPYExEtkd+s/fXAYV3Zv1c9AQ3xoqdeRsDejVa1mAVhlqBM/mEI3QNZBhaP6wxFKgo9k4xDNhMiN1BL0zdFvkvFr0wVP9SsK4H72McmKUQ1mTAvzIZ1q8=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
