travis:
  secure:
    BINSTAR_TOKEN: zSq3DXRFQALTQ4SGkrWCDSe7wbXs4Sx6EzM4YZ31gkvk54Jf4Qnp9fiV9J1eNgHYw2+w8P4CICLb/9w9m/KwN2FUDUYttSZbDtuurg5gAJuc6ILLE0mewIncnDR2//poTe+GQ5OSdZ9bIzBgU3dqZ7h8PM8IdkPQhdRJNdWHNpbI0TABoubLEFmRyAwWZuLlOjLP9JEc0wEdFzu5FI8yR4iCJS/kg3gerzBijL7RD6hhoM/FsbuskLRmnulZp/3NZcvSwtD0GD+K06d50BXBOZRfPC/hGou5FC2uv/zlEGQnGUNWcGV36bHLfaPJm0ymmVV/IBHcbzggADnmJeNdJPqOYGL8r81E4Lzd1PcVtoF7K6glKllxlIXJVVZpWoRNZjCS/H9+MwPUMSb72jYDw3zVbwu76Q6GuwGv470K/b6DoS0JK+Vtng/BV+Fj+G9wWKcgzNdPqRXq82leDPFPwyIXXm92sJEQhMC1DPJuZWMF1L+dSS3H4sxK0FDgsZyKZuQJVUdAfCD7AnRBYSHpJj/vSh3BIcTumv+SwzlqRZ2SBYkl4SlQgMj0UVfBbQl+rKgJ1l9gtjuUuZ4WJUQ8VI2W7M+BWFECsmEtXconR5fs4Wg83vrwRcghIeiKK4OUsUO5H7JmWRWW8hz7e1Gure7xW6JoTUeTIQA7q9K09MA=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
